BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `codesHistory` (
	`ids`	integer UNIQUE,
	`sequence`	text,
	`sequence_order`	integer,
	`locknums`	integer,
	`description`	text,
	`code1`	text,
	`code2`	text,
	`access_selection`	text,
	`starttime`	DATETIME,
	`endtime`	DATETIME,
	`status`	text,
	`access_count`	integer,
	`retry_count`	integer,
	`max_access`	integer,
	`max_retry`	integer,
	`access_time`	DATETIME,
	`admin_notification_sent`	BOOL,
	`user_notification_email`	text,
	`user_notification_sent`	BOOL,
	`answer1`	text,
	`answer2`	text,
	`answer3`	text,
	PRIMARY KEY(`ids`)
);
CREATE TABLE IF NOT EXISTS `codes` (
	`ids`	integer UNIQUE,
	`sequence`	text,
	`sequence_order`	integer,
	`locknums`	text,
	`description`	text,
	`code1`	text,
	`code2`	text,
	`starttime`	DATETIME,
	`endtime`	DATETIME,
	`fingerprint1`	integer,
	`fingerprint2`	integer,
	`status`	text,
	`access_count`	integer,
	`retry_count`	integer,
	`max_access`	integer,
	`max_retry`	integer,
	`lockbox_state`	integer,
	`ask_questions`	integer,
	`question1`	text,
	`question2`	text,
	`question3`	text,
	`access_type`	integer,
	PRIMARY KEY(`ids`)
);
CREATE TABLE IF NOT EXISTS `admin` (
	`ids`	integer UNIQUE,
	`admin_name`	text,
	`admin_email`	text,
	`admin_phone`	text,
	`default_report_freq`	DATETIME,
	`default_report_start`	DATETIME,
	`password`	text,
	`assist_password`	text,
	`show_fingerprint`	bool,
	`show_password`	bool,
	`show_takereturn`	bool,
	`use_predictive_access_code`	bool,
	`predictive_key`	text,
	`predictive_resolution`	integer,
	`max_locks`	text,
	`smtp_server`	text,
	`smtp_port`	text,
	`smtp_type`	text,
	`smtp_username`	text,
	`smtp_password`	text,
	`vnc_port`	text,
	`vnc_password`	text,
	`report_via_email`	text,
	`report_to_file`	text,
	`report_directory`	text,
	`display_power_down_timeout`	integer,
	`report_deletion`	DATETIME,
	PRIMARY KEY(`ids`)
);
COMMIT;
